name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: SudarshanHV/shared_workflows_demo/.github/workflows/simple-ci.yml@main
    with:
      app-name: "Hello Frontend"
      test-command: "npm test"

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    uses: SudarshanHV/shared_workflows_demo/.github/workflows/deploy.yml@main
    with:
      app-name: "sw-hello-frontend-demo"
      environment: "production"
