name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-with-coverage:
    uses: SudarshanHV/shared_workflows_demo/.github/workflows/react-coverage.yml@main
    with:
      app-name: "Hello Frontend"
      test-command: "npm test"
  
  coverage-upload:
    needs: test-with-coverage
    uses: SudarshanHV/shared_workflows_demo/.github/workflows/sonarqube.yml@main
    with:
      sonar-project-key: SudarshanHV_sw_hello_frontend_demo
      sonar-host-url: https://sonarcloud.io
      sonar-organization: sudarshanhv
      enable-coverage: true
    secrets: inherit

  deploy:
    needs: test-with-coverage
    if: github.ref == 'refs/heads/main'
    uses: SudarshanHV/shared_workflows_demo/.github/workflows/deploy.yml@main
    with:
      app-name: "sw-hello-frontend-demo"
      environment: "staging"
